baseurl = "http://ethereum.mochain.info" 
languageCode = "zh-cn"
title = "精通以太坊"
theme = "material"
metadataformat = "yaml"
canonifyurls = true
uglyURLs = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

# 启用rebots
enableRobotsTXT = false 

# If the Hugo site is versioned by Git, 
# you will then get a .GitInfo object per page, and 
# Lastmod will get updated by the last commit date for content.
# see: https://gohugo.io/variables/git/
enableGitInfo = false

# user pygment and 
pygmentsUseClassic = true 
pygmentsuseclasses = true
PygmentsCodeFences = true
pygmentsstyle = "friendly" 

[params]
	# General information
	author = "虞双齐"
	description = "从零成长为以太坊高级开发者"
	copyright = "根据Apache 2.0 许可发布"

	# Repository
	provider = "GitHub"
	repo_name = "mochain/etheraction"
	repo_url = "https://github.com/mochain/etheraction"

	version = "1.0.0"
	logo = "images/logo.png"
	icon = ""
	favicon = ""

	# Permanent link char , Default "¶" 
	permalink = ""

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	# Material supports both, left-to-right (ltr) and right-to-left (rtl) text direction, Default "ltr"
	direction = ""
	
	[params.plugins]
		search = true
	[params.palette]
		# red, pink, purple, deep purple, indigo, blue, light-blue, cyan, teal, green, light-green, lime, yellow, amber, orange, deep-orange, brown, grey and blue-grey. 
    	primary = "light-gren"
    	accent  = "indigo"

    [params.font]
		useimage = true
    	text = "Noto Sans CJK"
    	code = "Ubuntu Mono"
	
	[params.theme.feature]
		tabs = true

	[[params.social]] 
		type = "github"
		link= "https://github.com/ysqi"
	[[params.social]] 
		type = "wordpress"
		link= "https://yushuangqi.com"
	[[params.social]] 
		type = "weibo"
		link= "https://weibo.com/234665601"
	[[params.social]] 
		type = "user-circle"
		link= "https://www.zhihu.com/people/_ysqi/"	
	[[params.social]] 
		type = "envelope-o"
		link= "mailto:devysqi@gmail.com"	
 
[[menu.main]]
    name = "基础知识"
	url = "/basic/"
	identifier ="basic"
	weight = 10

[[menu.main]]
    name = "智能合约"
	url = "/contract/"
	identifier ="contract"
	weight = 20	

[[menu.main]]
    name = "Solidiy官方文档中文版"
	url = "/solidity/doc"
	identifier ="soliditydoc"
	weight = 30	
	
[[menu.main]]
    name = "实战"
	url = "/action" 
	identifier="action"
	weight = 40	 
	

[[menu.main]]
    name = "关于"
	url = "/about" 
	identifier="about"
	weight = 9000	 

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
 